In [1]:
# import data from hugging face
import pandas as pd

df = pd.read_csv("hf://datasets/alalfi/SupplyChainDataset/DataCoSupplyChainDataset1.csv")

c:\Users\mahmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
df.head(10)

Type  Days_for_shipping_(real)  Days_for_shipment_(scheduled)  \
0     DEBIT                         3                              4   
1  TRANSFER                         5                              4   
2      CASH                         4                              4   
3     DEBIT                         3                              4   
4   PAYMENT                         2                              4   
5  TRANSFER                         6                              4   
6     DEBIT                         2                              1   
7  TRANSFER                         2                              1   
8      CASH                         3                              2   
9      CASH                         2                              1   

   Benefit_per_order  Sales_per_customer    Delivery_Status  \
0           91.25000           314.64001   Advance shipping   
1         -249.09000           311.35999      Late delivery   
2         -247.78000           309.72000   Shipping on time   
3           22.86000           304.81000   Advance shipping   
4          134.21001           298.25000   Advance shipping   
5           18.58000           294.98001  Shipping canceled   
6           95.18000           288.42001      Late delivery   
7           68.43000           285.14001      Late delivery   
8          133.72000           278.59000      Late delivery   
9          132.14999           275.31000      Late delivery   

   Late_delivery_risk  Category_Id   Category_Name Customer_City  ...  \
0                   0           73  Sporting Goods        Caguas  ...   
1                   1           73  Sporting Goods        Caguas  ...   
2                   0           73  Sporting Goods      San Jose  ...   
3                   0           73  Sporting Goods   Los Angeles  ...   
4                   0           73  Sporting Goods        Caguas  ...   
5                   0           73  Sporting Goods     Tonawanda  ...   
6                   1           73  Sporting Goods        Caguas  ...   
7                   1           73  Sporting Goods         Miami  ...   
8                   1           73  Sporting Goods        Caguas  ...   
9                   1           73  Sporting Goods     San Ramon  ...   

  Order_Zipcode Product_Card_Id Product_Category_Id  Product_Description  \
0           NaN            1360                  73                  NaN   
1           NaN            1360                  73                  NaN   
2           NaN            1360                  73                  NaN   
3           NaN            1360                  73                  NaN   
4           NaN            1360                  73                  NaN   
5           NaN            1360                  73                  NaN   
6           NaN            1360                  73                  NaN   
7           NaN            1360                  73                  NaN   
8           NaN            1360                  73                  NaN   
9           NaN            1360                  73                  NaN   

                                 Product_Image Product_Name Product_Price  \
0  http://images.acmesports.sports/Smart+watch  Smart watch        327.75   
1  http://images.acmesports.sports/Smart+watch  Smart watch        327.75   
2  http://images.acmesports.sports/Smart+watch  Smart watch        327.75   
3  http://images.acmesports.sports/Smart+watch  Smart watch        327.75   
4  http://images.acmesports.sports/Smart+watch  Smart watch        327.75   
5  http://images.acmesports.sports/Smart+watch  Smart watch        327.75   
6  http://images.acmesports.sports/Smart+watch  Smart watch        327.75   
7  http://images.acmesports.sports/Smart+watch  Smart watch        327.75   
8  http://images.acmesports.sports/Smart+watch  Smart watch        327.75   
9  http://images.acmesports.sports/Smart+watch  Smart watch        327.75   

  Product_Status shipping_date_

In [16]:
df.columns

Index(['Type', 'Days_for_shipping_(real)', 'Days_for_shipment_(scheduled)',
       'Benefit_per_order', 'Sales_per_customer', 'Delivery_Status',
       'Late_delivery_risk', 'Category_Id', 'Category_Name', 'Customer_City',
       'Customer_Country', 'Customer_Email', 'Customer_Fname', 'Customer_Id',
       'Customer_Lname', 'Customer_Password', 'Customer_Segment',
       'Customer_State', 'Customer_Street', 'Customer_Zipcode',
       'Department_Id', 'Department_Name', 'Latitude', 'Longitude', 'Market',
       'Order_City', 'Order_Country', 'Order_Customer_Id',
       'order_date_(DateOrders)', 'Order_Id', 'Order_Item_Cardprod_Id',
       'Order_Item_Discount', 'Order_Item_Discount_Rate', 'Order_Item_Id',
       'Order_Item_Product_Price', 'Order_Item_Profit_Ratio',
       'Order_Item_Quantity', 'Sales', 'Order_Item_Total',
       'Order_Profit_Per_Order', 'Order_Region', 'Order_State', 'Order_Status',
       'Order_Zipcode', 'Product_Card_Id', 'Product_Category_Id',
       'Product_De

In [ ]:
df[['Delivery_Status']].value_counts() / df.shape[0]


Delivery_Status  
Late delivery        0.548291
Advance shipping     0.230402
Shipping on time     0.178352
Shipping canceled    0.042954
Name: count, dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   Type                           180519 non-null  object 
 1   Days_for_shipping_(real)       180519 non-null  int64  
 2   Days_for_shipment_(scheduled)  180519 non-null  int64  
 3   Benefit_per_order              180519 non-null  float64
 4   Sales_per_customer             180519 non-null  float64
 5   Delivery_Status                180519 non-null  object 
 6   Late_delivery_risk             180519 non-null  int64  
 7   Category_Id                    180519 non-null  int64  
 8   Category_Name                  180519 non-null  object 
 9   Customer_City                  180519 non-null  object 
 10  Customer_Country               180519 non-null  object 
 11  Customer_Email                 180519 non-null  object 
 12  Customer_Fname                

In [ ]:
df.isnull().sum()

Type                                  0
Days_for_shipping_(real)              0
Days_for_shipment_(scheduled)         0
Benefit_per_order                     0
Sales_per_customer                    0
Delivery_Status                       0
Late_delivery_risk                    0
Category_Id                           0
Category_Name                         0
Customer_City                         0
Customer_Country                      0
Customer_Email                        0
Customer_Fname                        0
Customer_Id                           0
Customer_Lname                        8
Customer_Password                     0
Customer_Segment                      0
Customer_State                        0
Customer_Street                       0
Customer_Zipcode                      3
Department_Id                         0
Department_Name                       0
Latitude                              0
Longitude                             0
Market                                0


In [ ]:
df.describe()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pan

Days_for_shipping_(real)  Days_for_shipment_(scheduled)  \
count             180519.000000                  180519.000000   
mean                   3.497654                       2.931847   
std                    1.623722                       1.374449   
min                    0.000000                       0.000000   
25%                    2.000000                       2.000000   
50%                    3.000000                       4.000000   
75%                    5.000000                       4.000000   
max                    6.000000                       4.000000   

       Benefit_per_order  Sales_per_customer  Late_delivery_risk  \
count      180519.000000       180519.000000       180519.000000   
mean           21.974989          183.107609            0.548291   
std           104.433526          120.043670            0.497664   
min         -4274.979980            7.490000            0.000000   
25%             7.000000          104.380000            0.000000   
50%            31.520000          163.990010            1.000000   
75%            64.800000          247.399990            1.000000   
max           911.799990         1939.989990            1.000000   

         Category_Id    Customer_Id  Customer_Zipcode  Department_Id  \
count  180519.000000  180519.000000     180516.000000  180519.000000   
mean       31.851451    6691.379495      35921.126914       5.443460   
std        15.640064    4162.918106      37542.461122       1.629246   
min         2.000000       1.000000        603.000000       2.000000   
25%        18.000000    3258.500000        725.000000       4.000000   
50%        29.000000    6457.000000      19380.000000       5.000000   
75%        45.000000    9779.000000      78207.000000       7.000000   
max        76.000000   20757.000000      99205.000000      12.000000   

            Latitude  ...  Order_Item_Quantity          Sales  \
count  180519.000000  ...        180519.000000  180519.000000   
mean       29.719955  ...             2.127638     203.772097   
std         9.813646  ...             1.453451     132.273077   
min       -33.937550  ...             1.000000       9.990000   
25%        18.265430  ...             1.000000     119.980000   
50%        33.144860  ...             1.000000     199.920000   
75%        39.279620  ...             3.000000     299.950010   
max        48.781930  ...             5.000000    1999.989990   

       Order_Item_Total  Order_Profit_Per_Order  Order_Zipcode  \
count     180519.000000           180519.000000   24843.000000   
mean         183.107609               21.974989   55420.648070   
std          120.043670              104.433526   31921.252921   
min            7.490000            -4274.980000    1040.000000   
25%          104.380000                7.000000   23464.000000   
50%          163.990010               31.520000   59405.000000   
75%          247.399990               64.800000   90008.000000   
max         1939.989990              911.800000   99301.000000   

       Product_Card_Id  Product_Category_Id  Product_Description  \
count    180519.000000        180519.000000                  0.0   
mean        692.509764            31.851451                  NaN   
std         336.446807            15.640064                  NaN   
min          19.000000             2.000000                  NaN   
25%         403.000000            18.000000                  NaN   
50%         627.000000            29.000000                  NaN   
75%        1004.000000            45.000000                  NaN   
max        1363.000000            76.000000                  NaN   

       Product_Price  Product_Status  
count  180519.000000        180519.0  
mean      141.232547             0.0  
std       139.732489             0.0  
min         9.990000             0.0  
25%        50.000000             0.0  
50%        59.990000             0.0  
75%       199.990000             0.0  
max      1999.990000             0.0  

[8 r

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   Type                           180519 non-null  object 
 1   Days_for_shipping_(real)       180519 non-null  int64  
 2   Days_for_shipment_(scheduled)  180519 non-null  int64  
 3   Benefit_per_order              180519 non-null  float64
 4   Sales_per_customer             180519 non-null  float64
 5   Delivery_Status                180519 non-null  object 
 6   Late_delivery_risk             180519 non-null  int64  
 7   Category_Id                    180519 non-null  int64  
 8   Category_Name                  180519 non-null  object 
 9   Customer_City                  180519 non-null  object 
 10  Customer_Country               180519 non-null  object 
 11  Customer_Email                 180519 non-null  object 
 12  Customer_Fname                

In [ ]:
df['Type'].unique()

array(['DEBIT', 'TRANSFER', 'CASH', 'PAYMENT'], dtype=object)

In [ ]:
for _ in df:
    print(df[_].unique(),'\n')

['DEBIT' 'TRANSFER' 'CASH' 'PAYMENT'] 

[3 5 4 2 6 0 1] 

[4 1 2 0] 

[  91.25    -249.09    -247.78    ... -103.97    -237.59    -337.10001] 

[314.64001 311.35999 309.72    ... 298.76999 403.70999 474.76001] 

['Advance shipping' 'Late delivery' 'Shipping on time' 'Shipping canceled'] 

[0 1] 

[73 17 29 24 13 12  9 41 37 38 44  3 18 43 65 62 64  4  2 26 40 76 66 70
  6 11 16 36 10 63  5 60 45 59 67 61 68  7 72 69 71 75 35 34 33 32 31 30
 74 48 46] 

['Sporting Goods' 'Cleats' 'Shop By Sport' "Women's Apparel" 'Electronics'
 'Boxing & MMA' 'Cardio Equipment' 'Trade-In' "Kids' Golf Clubs"
 'Hunting & Shooting' 'Baseball & Softball' "Men's Footwear"
 'Camping & Hiking' 'Consumer Electronics' 'Cameras' 'Computers'
 'Basketball' 'Soccer' "Girls' Apparel" 'Accessories' "Women's Clothing"
 'Crafts' "Men's Clothing" 'Tennis & Racquet' 'Fitness Accessories'
 'As Seen on  TV!' 'Golf Balls' 'Strength Training' "Children's Clothing"
 'Lacrosse' 'Baby' 'Fishing' 'Books' 'DVDs' 'CDs' 'Garden' 'Ho

In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report , f1_score, recall_score, precision_score
import matplotlib.pyplot as plt

# Load data

# =============================================
# 1. DATA CLEANING & FEATURE SELECTION
# =============================================

def clean_numeric(col):
    """Fix problematic numeric columns"""
    if pd.api.types.is_string_dtype(col):
        col = col.str.replace(',', '').str.replace('k', '000')
        col = col.str.replace(r'(\d+)\.(\d+)\.(\d+)', r'\1\2.\3', regex=True)
    return pd.to_numeric(col, errors='coerce')

# Clean numeric columns
numeric_cols = ['Benefit_per_order', 'Sales_per_customer', 'Order_Item_Product_Price',
                'Order_Item_Total', 'Order_Profit_Per_Order', 'Product_Price']
for col in numeric_cols:
    df[col] = clean_numeric(df[col])

# Selected features (mix of numeric and categorical)
features = [
    # Numeric features
    'Days_for_shipping_(real)',
    'Days_for_shipment_(scheduled)',
    'Order_Item_Quantity',
    'Order_Item_Discount_Rate',
    'Benefit_per_order',
    'Order_Item_Profit_Ratio',
    'Late_delivery_risk',  # Binary feature

    # Categorical features (will be encoded)
    'Shipping_Mode',
    'Market',
    'Order_Region',
    'Customer_Country'
]

# Target variable
target = 'Delivery_Status'

# Create working dataframe
model_df = df[features + [target]].copy()

# =============================================
# 2. FEATURE ENCODING
# =============================================

# Initialize encoders dictionary to store mappings
encoders = {}

# Encode categorical features
categorical_cols = ['Shipping_Mode', 'Market', 'Order_Region', 'Customer_Country']
for col in categorical_cols:
    le = LabelEncoder()
    model_df[col] = le.fit_transform(model_df[col].astype(str))
    encoders[col] = le  # Store encoder for reference

    # Print encoding mapping
    print(f"\n{col} Encoding:")
    print(dict(zip(le.classes_, range(len(le.classes_)))))

# Encode target variable
target_encoder = LabelEncoder()
model_df[target] = target_encoder.fit_transform(model_df[target])
print(f"\nTarget ({target}) Encoding:")
print(dict(zip(target_encoder.classes_, range(len(target_encoder.classes_)))))

# =============================================
# 3. DATA SPLITTING
# =============================================

X = model_df.drop(target, axis=1)
y = model_df[target]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# =============================================
# 4. XGBOOST MODEL TRAINING
# =============================================

model = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    objective='multi:softmax',
    eval_metric='mlogloss',
    random_state=42,
    early_stopping_rounds=10
)

# Train with validation set
model.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    verbose=True
)

# =============================================
# 5. MODEL EVALUATION
# =============================================

# Predictions
y_pred = model.predict(X_test)

# Metrics
print("\nModel Performance:")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print("\nClassification Report:")
print(classification_report(
    y_test, y_pred,
    target_names=target_encoder.classes_
))
print(f1_score(y_pred, y_test, average = 'samples'))

# Feature Importance
plt.figure(figsize=(10, 6))
plt.barh(X.columns, model.feature_importances_)
plt.title("Feature Importance")
plt.tight_layout()
plt.show()

# Learning Curve
results = model.evals_result()
plt.figure(figsize=(10, 6))
plt.plot(results['validation_0']['mlogloss'], label='Validation Loss')
plt.legend()
plt.title("XGBoost Learning Curve")
plt.show()


Shipping_Mode Encoding:
{'First Class': 0, 'Same Day': 1, 'Second Class': 2, 'Standard Class': 3}

Market Encoding:
{'Africa': 0, 'Europe': 1, 'LATAM': 2, 'Pacific Asia': 3, 'USCA': 4}

Order_Region Encoding:
{'Canada': 0, 'Caribbean': 1, 'Central Africa': 2, 'Central America': 3, 'Central Asia': 4, 'East Africa': 5, 'East of USA': 6, 'Eastern Asia': 7, 'Eastern Europe': 8, 'North Africa': 9, 'Northern Europe': 10, 'Oceania': 11, 'South America': 12, 'South Asia': 13, 'South of  USA': 14, 'Southeast Asia': 15, 'Southern Africa': 16, 'Southern Europe': 17, 'US Center': 18, 'West Africa': 19, 'West Asia': 20, 'West of USA': 21, 'Western Europe': 22}

Customer_Country Encoding:
{'EE. UU.': 0, 'Puerto Rico': 1}

Target (Delivery_Status) Encoding:
{'Advance shipping': 0, 'Late delivery': 1, 'Shipping canceled': 2, 'Shipping on time': 3}
[0]	validation_0-mlogloss:1.20277
[1]	validation_0-mlogloss:1.05558
[2]	validation_0-mlogloss:0.93399
[3]	validation_0-mlogloss:0.83157
[4]	validation_0-ml

ValueError: Samplewise metrics are not available outside of multilabel classification.